### ISSUE TITLE
Bluetooth keyboard layout

### ISSUE THREAD

**Issue by sousaaguilherme** [VoidNoi/BadCard#12]
Any plans on adding layouts to the bluetooth functionality?

Thanks!!

**Comment by VoidNoi** [comment]
Hi. Yes, this has been a planned feature from the beginning. I haven't been able to add it yet because the libraries for USB and BLE work slightly differently when sending the scancodes. I found out something recently that might make this possible, but please don't get your hopes up as I haven't tested it yet.

**Comment by sousaaguilherme** [comment]
Great! Thanks for all the effort!
