### ISSUE TITLE
Subfolder Navigation

### ISSUE THREAD

**Issue by WholeWheatBrad** [VoidNoi/BadCard#2]
I would really love the ability to navigate through folders inside of /Badcard

eg: /Badcard/Windows -> select script.

**Comment by VoidNoi** [comment]
In order to add this I would need to change many things about the code like the way menus are handled, adding an option to create folders directly from the cardputer as well as the way the files created from the cardputer are saved. I won't say I'm not gonna add this but if I do it won't be any time soon since there's more important features to be implemented.

**Comment by VoidNoi** [comment]
This function has been added! https://github.com/VoidNoi/BadCard/releases/tag/v1.6.0
